console.log("JS_week 12");

let main_div = document.getElementById("main_div");

let para = document.createElement("p");

para.innerText = "This is paragraph generated by js";

main_div.innerHTML = para.outerHTML;
// main_div.appendChild(para);


let td_element1 = document.createElement("td");
let td_element2 = document.createElement("td");
let td_element3 = document.createElement("td");

let tr_element = document.createElement("tr");

let table_elememt = document.createElement("table");

// td_element1.innerHTML = "COl 1";

// tr_element.appendChild(td_element1);

// td_element2.innerHTML = "COl 2";

// tr_element.appendChild(td_element2);

// td_element3.innerHTML = "COl 3";

// tr_element.appendChild(td_element3);

// table_elememt.appendChild(tr_element);

// main_div.appendChild(table_elememt);



const tr_data = "<tr> <td> Hey </td> <td> How </td> </td> <td> Are </td> </tr>";

tr_element.innerHTML = tr_data;

table_elememt.appendChild(tr_element);
main_div.appendChild(table_elememt);

let attr = document.createAttribute("border");

attr.value = "1";

table_elememt.setAttributeNode(attr);